#!/bin/bash

#PBS -V
#PBS -N cancer_subtypes
#PBS -m abe
#PBS -M grahman@eng.ucsd.edu
#PBS -l pmem=16gb
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=10

source /opt/miniconda3/bin/activate CancerSubtypes

#Rscript='/home/grahman/.conda/envs/CancerSubtypes/bin/Rscript'
#source activate CancerSubtypes
#$Rscript /home/grahman/projects/rotation_2019/cancer_subtypes/cancer_subtypes_test.R

Rscript /home/grahman/projects/rotation_2019/cancer_subtypes/cancer_subtypes_test.R
