#!/bin/bash

#PBS -V
#PBS -N anova
#PBS -m abe
#PBS -M grahman@eng.ucsd.edu
#PBS -l pmem=8gb
#PBS -l walltime=24:00:00
#PBS -l nodes=2:ppn=10
#PBS -j oe
#PBS -o out/

source /opt/miniconda3/bin/activate CancerSubtypes

cib_script='/home/grahman/projects/rotation_2019/stats/cib_anova.R'
otu_script='/home/grahman/projects/rotation_2019/stats/otu_anova.R'

Rscript $cib_script $CLUST_DIR $CIB_FILE
Rscript $otu_script $CLUST_DIR $OTU_FILE
