#!/bin/bash

#PBS -V
#PBS -t 1-25
#PBS -N surv_analysis
#PBS -m abe
#PBS -M grahman@eng.ucsd.edu
#PBS -l pmem=8gb
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=10
#PBS -j oe
#PBS -o out/

source /opt/miniconda3/bin/activate CancerSubtypes
script='/home/grahman/projects/rotation_2019/stats/survival_analysis.R'
cancers='/home/grahman/projects/rotation_2019/data/cancer_counts.txt'

Rscript $script `sed -n "${PBS_ARRAYID}p" $cancers`
